#!/bin/sh

# * docker: rootfs megnovelese
# * docker: fsck futtatása az elkeszult particion
# * root user jelszo beallitas
# docker: openssh-server telepitese
# locales
# utolsó particio atmeretezese

export LANG=C

# based on raspi-config
do_expand_rootfs() {
  ROOT_PART=$(mount | grep ' on / type ' | awk '{print $1}' | sed 's/^\/dev\///')
  PART_NUM=${ROOT_PART#mmcblk0p}
  if [ "$PART_NUM" = "$ROOT_PART" ]; then
    echo "$ROOT_PART is not an SD card. Don't know how to expand"
    return 0
  fi

  # NOTE: the NOOBS partition layout confuses parted. For now, let's only 
  # agree to work with a sufficiently simple partition layout
  if [ "$PART_NUM" -ne 2 ]; then
    echo "Your partition layout is not currently supported by this tool. You are probably using NOOBS, in which case your root filesystem is already expanded anyway."
    return 0
  fi

  LAST_PART_NUM=$(sfdisk -l /dev/mmcblk0 | tail -n 1 | cut -f 1 -d' ' | sed 's/\/dev\/mmcblk0p//')

  if [ "$LAST_PART_NUM" != "$PART_NUM" ]; then
    echo "/dev/root is not the last partition. Don't know how to expand"
    return 0
  fi

  # Get the starting offset of the root partition
  PART_START=$(sfdisk -l /dev/mmcblk0 | grep "^/dev/mmcblk0p${PART_NUM}" | awk '{print $2}')
  [ "$PART_START" ] || return 1
  # Return value will likely be error for fdisk as it fails to reload the
  # partition table because the root fs is mounted
  fdisk /dev/mmcblk0 <<EOF
p
d
$PART_NUM
n
p
$PART_NUM
$PART_START

p
w
EOF

  # now set up an init.d script
cat <<\EOF > /etc/init.d/resize2fs_once &&
#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once" &&
    ROOT_DEV=$(mount | grep ' on / type ' | awk '{print $1}')
    resize2fs ${ROOT_DEV} &&
    rm /etc/init.d/resize2fs_once &&
    update-rc.d resize2fs_once remove &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
EOF
  chmod +x /etc/init.d/resize2fs_once &&
  update-rc.d resize2fs_once defaults &&
  echo "Root partition has been resized."
  echo "The filesystem will be enlarged upon the next reboot"
  echo 'Reboot now? (y/N)' && read x && [ "$x" = "y" ] && /sbin/reboot;
}


do_expand_rootfs
