#!/bin/sh

# * docker: rootfs megnovelese
# * docker: fsck futtatása az elkeszult particion
# * root user jelszo beallitas
# docker: openssh-server telepitese
# locales
# utolsó particio atmeretezese


DEV=mmcblk0

PARTED=$(parted $DEV unit s print | sed '/^$/d' | tail -n1)
PART_NO=$(echo $PARTED | awk '{ print $1 }')
PART_START=$(echo $PARTED | awk '{ gsub("s","",$2); print $2 }')

echo $PART_NO $PART_START


