#!/bin/sh

set -xue

cd "$(dirname "$(readlink -f "$0")")/.."

#sudo rm -f build/rootfs.tgz
docker-compose build
docker-compose up
CONTAINER=$(docker-compose ps | grep '^\w' | cut -d' ' -f1)
docker cp ${CONTAINER}:/usr/local/image-builder/workdir/boot.img ..
